### ISSUE TITLE
Recording storage usage

### ISSUE THREAD

**Issue by sorrison** [Karaage-Cluster/karaage#101]
This is a request for a future ability for Karaage. Happy to discuss this as to what options are used, what is the best way to do it, etc.

Basically, looking to record storage for users, projects and institutions. Understandably not all this information is always available so this is an optional feature.

Information should be available to be pulled from multiple locations, and reported on those locations individually and as a sum.

**Comment by brianmay** [comment]
Doing this requires the new tables that are part of the karaage4 branch.

**Comment by brianmay** [comment]
See #430.
