### ISSUE TITLE
Choice to email (or not) non active accounts

### ISSUE THREAD

**Issue by cwestvpac** [Karaage-Cluster/karaage#134]
When sending emails in Karaage it appears to send to all members, including non active accounts.

It would be nice if this was an option... default option to not email active accounts, with a tick box to allow that you to send to all accounts (including inactive).

**Comment by DanielTosello** [comment]
I believe this is actually implemented now.

**Comment by brianmay** [comment]
Karaage no now longer emails locked accounts. Any objections to closing this?

**Comment by brianmay** [comment]
Closing.
