### ISSUE TITLE
[django-tables2] AttributeError: 'GenericForeignKey' object has no attribute 'verbose_name' (django 1.8)

### ISSUE THREAD

**Issue by brianmay** [Karaage-Cluster/karaage#265]
This is a django-tables2 bug, see https://github.com/bradleyayers/django-tables2/issues/237 and https://github.com/bradleyayers/django-tables2/issues/247.

**Comment by brianmay** [comment]
Confirmed this is still a problem in django-tables2 version 1.0.4 uploaded 2015-05-09.

**Comment by igorgai** [comment]
For anyone struggling with this issue using following fork may help: https://github.com/bdauvergne/django-tables2. 

There's a commit solving this problem: https://github.com/bdauvergne/django-tables2/commit/423a74702c7bff58cbe8f9078c5241b99ba3bb77

**Comment by brianmay** [comment]
A lot has changed, and the stupid idiot reporter didn't give any steps on how to reproduce. Oh wait... That was me....

Going to assume this error was seen running tests, and I am not seeing this error running tests right now. I am going to assume this is fixed now.
