### ISSUE TITLE
Karaage3 now directly emails admins for admin action requests, not our RT system

### ISSUE THREAD

**Issue by chrissamuel** [Karaage-Cluster/karaage#267]
Hiya Brian,

Previously in Karaage2 it would send emails for admin actions (approving users, removing users, etc) to a defined address which for us was a special RT queue so we could track them (and not lose them).

However, on upgrading to Karaage3 it now emails people marked as Karaage administrators directly instead.

How can we reinstate the old behaviour of emails going to to a single address (not associated with an admin account) instead please?

thanks!
Chris

**Comment by brianmay** [comment]
Fixed in 9ebc3d0c5744b2477631f93ba3536eb785f5bf51.
