### ISSUE TITLE
Duplicate user process is confusing

### ISSUE THREAD

**Issue by AndrewIsaac** [Karaage-Cluster/karaage#280]
Duplicate user process is confusing
After inviting, leaders see same page where only button is the 'Duplicate' button, so they often click it.
Would also be good to show potential matches based on name, email, (other?) and point out that just because no match was found, it is still worth checking..

**Comment by chrissamuel** [comment]
Agreed, currently when you're approving someone who doesn't already exist in the
system Karaage will tell you:

Please check that the applicant isn't an existing user.
No items.

It might be better for the "No items" to say (including brackets):

(No potential duplicates found, please check manually)

Just to make it a bit more obvious what has happened there.

**Comment by brianmay** [comment]
Ok, so we should change the "No items" text to "(No potential duplicates found, please check manually)".

Is that change by itself sufficient? Otherwise is there anything else that could be changed to make it less confusing?

Or is it a matter "make this change now and see what happens?"
