### ISSUE TITLE
Institute Delegates that have `Send email:` unchecked still get emails

### ISSUE THREAD

**Issue by AndrewIsaac** [Karaage-Cluster/karaage#447]
Institute Delegates that have `Send email:` unchecked still get emails
A previous request/fix (#438) was to allow Institute Delegates that have `Send email:` unchecked to still be able to approve an application at the Institute Delegate level (previously they could only cancel/decline).  This has had a side effect that those delegates now receive all Institute Delegate emails.

I want to keep the functionality of 'silent' Institute Delegates being able to approve applications, so need to debug email sending.

I'll have a quick look, but don't fully understand state machine 'magic' of application process.

**Comment by brianmay** [comment]
Apologies for this. The relevant code is the `StateWaitingForApproval` class in `karaage/plugins/kgapplications/views/states.py`. As you can see we use the same function `get_authorised_persons` to check "is this person authorised" as well as to get a list of people we should email. Maybe we should have a new method `get_email_persons` (can you think of a better name?) that defaults to calling `get_authorised_persons` and can be overridden by the `StateWaitingForDelegate` class. Does this make sense?

**Comment by AndrewIsaac** [comment]
no prob -- tricky to spot side effect
I'm working on a more generic fix.
Just a `try: filter(send_email=true) except...` at line 71 of `karaage/plugins/kgapplications/views/states.py`
That way if any `get_authorised_persons` has a send_email property they can be filtered out (in).
Might be useful for admins, leaders, etc who don't want to be emailed (potential feature request).
Hope that make sense.
PS I've started testing, but probably wont get back to it until Mon.

**Comment by AndrewIsaac** [comment]
You are right, `send_email` is a property of the role, not the person, so too messy to do generically.
Should be a function of the role/state.
I'll give it a go today.

**Comment by AndrewIsaac** [comment]
I've created branch `issue-#447` of tag v5.0.7
I've tested and works for me
Not sure if you want to merge into master or new tag (or both)...
Would be good if it could be deployed into non-beta build for deployment
ta

**Comment by brianmay** [comment]
AndrewIsaac <notifications@github.com> writes:

> I've created branch `issue-#447` of tag v5.0.7
> I've tested and works for me
> Not sure if you want to merge into master or new tag (or both)...
> Would be good if it could be deployed into non-beta build for
> deployment

Can you please create a pull request?

Thanks.
-- 
Brian May <brian@linuxpenguins.xyz>
https://linuxpenguins.xyz/brian/

**Comment by brianmay** [comment]
I believe this should be working as required now. Closing.
