### ISSUE TITLE
Feature request: better handling of 'add user to project' workflow

### ISSUE THREAD

**Issue by DanielTosello** [Karaage-Cluster/karaage#450]
At the moment there are two places a project administrator needs to know about to add users to their project: The 'add existing user' field and the 'invite a new user' field...  there's no indication in advance how these differ if the user isn't savvy, and attempting to send a new user email to an existing user results in a nonfatal error that confuses project admins... and it generally comes up when they're importing large amounts of students at once.

Additionally, i believe functionality to determine whether an email address belongs to an existing user (or a new invitation needs to be sent) already exists in the karaage codebase.

So... 

Can we unify those two controls and have karaage determine in the background which action is the appropriate one?

**Comment by brianmay** [comment]
Daniel Tosello <notifications@github.com> writes:

> At the moment there are two places a project administrator needs to know about to add users to their project: The 'add existing user' field and the 'invite a new user' field...  there's no indication in advance how these differ if the user isn't savvy, and attempting to send a new user email to an existing user results in a nonfatal error that confuses project admins... and it generally comes up when they're importing large amounts of students at once.
>
> Additionally, i believe functionality to determine whether an email address belongs to an existing user (or a new invitation needs to be sent) already exists in the karaage codebase.
>
> So... 
>
> Can we unify those two controls and have karaage determine in the background which action is the appropriate one?


What would you like to see? Maybe both buttons send an invitation?

Is there any use case for the other function?
-- 
Brian May <brian@linuxpenguins.xyz>
https://linuxpenguins.xyz/brian/

**Comment by DanielTosello** [comment]
Ideally if they have an existing account it just resolves it and adds the user without prompting them, and invokes the new user application process otherwise.

I'd eventually also like to expose some of the batch invite functionality here too, but that needs polish to work on the web interface.

**Comment by brianmay** [comment]
Maybe this is just me, but I worry that this could be confusing from the user's point of view. i.e. having a button that sometimes adds the user immediately without any prompting, and sometimes going through a full application process that requires project manager and system administrator approval. Plus skipping the application process will skip the emailing of the other project leaders and system administrators meaning there is reduced audit trail of changes.

**Comment by DanielTosello** [comment]
They're already confused though...

They think they're performing the action of 'adding a user to my project',
they don't necessarily see the distinction between new and existing users,
and don't know they need record to that information in advance... the
difference kind of shouldn't matter to them either.

Timing delays already exist in the current process because the approval
process relies on external factors, so there's no necessary consistency for
timing for approvals to interrupt... i see what you're saying but it seems
to me like this is already the current state of play.

**Comment by brianmay** [comment]
Ideally we need the best solution, not just a solution that is less confusing then what we already have.

> "they don't necessarily see the distinction between new and existing users"

Yes, my point exactly. This means both actions should do the same thing, that is go through the full application process.

Otherwise they do need to understand the distinction between new and existing users because the process will be very different for both cases.

**Comment by DanielTosello** [comment]
I don't understand. What part of the process, as far as the inviter is
concerned?

In my proposed solution, either the invited user will be added to the
project via their existing user credentials or they will have a new user
signup process initiated...

**Comment by brianmay** [comment]
If you don't think this is confusing (sometimes a user is added immediately without any approval vs sometimes via the sign up process and requires both project leader and sysadmin approval), then this is fine with me. Will look at implementation.

**Comment by brianmay** [comment]
Oh, wait a moment, I see the problem: "attempting to send a new user email to an existing user results in a nonfatal error that confuses project admins".

I believe inviting an existing person to a project is suppose to work. Can you please provide a screenshot of this error?

Looking at the code, I see a confirmation asking if the admin wants to continue if the user already exists, but maybe this confirmation is confusing, broken, or not required? Maybe users are mistaking this confirmation message for a error message?

**Comment by brianmay** [comment]
As an example, this is a message I get when I tried to invite myself to a project:

![karaage](https://user-images.githubusercontent.com/112729/42986342-80c142d6-8c38-11e8-9335-f0c54d9baad7.png)

**Comment by DanielTosello** [comment]
That's... odd. Looks like it already does do what i'd suggest to resolve
the customer's issue here...

I think i should have looked at the code closer first on this, i've been
too rushed.

Sorry, leave it with me. I'll look into it today.

**Comment by DanielTosello** [comment]
Hahah :/

Thanks for that... looks like the 500 is still being returned though, so i
guess that's not the only issue. I'll actually look at the logs today, i
should actually have time :/

**Comment by DanielTosello** [comment]
haha it's the other obvious collision case causing the 500 i saw: the
invited user is the same as the authenticated user making the request. I
guess it's probably worth adding another check to make sure those two don't
match.

**Comment by DanielTosello** [comment]
Looks good to me, though i'd probably name project_common_invite_multiple.html differently (because i'm planning on building forms or related functionality for multiple simultaneous invites that will eventually tie into this... though it might be easier to build that into the existing request form instead).

**Comment by brianmay** [comment]
If you can think of a better name, let me know and I will rename it :-)

**Comment by brianmay** [comment]
From the perspective of a user, yes, might be less confusing if you have one form that can be used for multiple or single invites.

**Comment by DanielTosello** [comment]
Also csv uploads or whatever would be useful and i know the functionality
already exists... but that's a discussion for elsewhere.
