### ISSUE TITLE
LDAP record gidnumber set to institution rather than project

### ISSUE THREAD

**Issue by DanielTosello** [Karaage-Cluster/karaage#469]
Karaage is set up to allow users to choose their default project via the frontend & sets this in db but never seems to get set it in their ldap record.

E.g. I set my default group to, for example, 'admin'. when doing `id` on the command line i'm still returned 'institution' as gid, with 'admin' an entry in the groups list.

This may actually be a lingering model issue, i remember we had a problem with this interface breaking a while back.

**Comment by brianmay** [comment]
This is probably because Karaage is configured to set gid to the institute, not the project...

**Comment by DanielTosello** [comment]
Facepalm.
It's PRIMARY_GROUP in the LDAP datastores block, isn't it?

Changed it to 'default_project', based on the code. Hope that's correct.

sorry for bothering you, thanks for the help :)

**Comment by brianmay** [comment]
No problem. That all sounds correct to me.
