### ISSUE TITLE
Adding an institute sometimes attempts to add wrong or null group_id

### ISSUE THREAD

**Issue by DanielTosello** [Karaage-Cluster/karaage#476]
I was seeing 500s returned from submitting the add institute form (institutes/add/). 

Looking through the logs i noticed that group_id was null (& of course throwing a nice stacktrace)... and i realised i'd forgotten to report a previous bug which caused institutes to be associated with valid but incorrect groups... which, of course, messed with their posix groups.

Then, when manually adding the entry to the db i noticed that the auto-increment for the institute id had advanced an equal number of entries to the number of failures i'd had, but so had the auto-increment in the people_group table... i haven't checked the code yet but... it seems likely that this is caused by an error in the generation of groups to associate the institute with, possibly something that causes two separate db rollbacks.

**Comment by brianmay** [comment]
I am not a fan of groups in Karaage. I have been trying to find a sane way to fix them. Having said that, they should not be causing crashes.

Oh, I see the problem:

```
   def save(self, commit=True):
        institute = super(InstituteForm, self).save(commit=True)
        if institute.group_id is None:
            name = self.cleaned_data['group_name']
            institute.group, _ = Group.objects.get_or_create(name=name)
        return institute
```

If there is no group, we try to set a group. Except we have already crashed trying to save it in the previous line. Oops. I should be able to fix this.

I can't comprehend the other part of this bug report. Maybe if you open another bug report, and say what you have done, what results you expected to see, and what actually happened?

**Comment by brianmay** [comment]
Appears I didn't actually fix the problem I was aiming to fix, Or maybe changes in Django broken things. I think I have a real fix now.

**Comment by brianmay** [comment]
Fixed version on http://karaage-test.hpc.unimelb.edu.au/karaage/ if you want to test it.

**Comment by brianmay** [comment]
Just deployed the fixed version to dashboard.

**Comment by DanielTosello** [comment]
Thankyou. You're a legend.
