### ISSUE TITLE
Feature Request: add all groups to Group dropdown in Send Email menu

### ISSUE THREAD

**Issue by DanielTosello** [Karaage-Cluster/karaage#496]
In addition to the existing choices in the Send Email menu, it would be good to be able to send an email to a specific project or software group.

Can we unroll those groups onto the end of the EMAIL_GROUPS list in master/karaage/emails/forms.py? it's fine (probably better) if their labels are just their group names... (i.e group 'punim0001' should display as 'punim001' in the list)

Of course, in our case this will create a list several hundred entries long... but that's expected.

EDIT: Ben Moran has just informed me of some VSLCI code for doing this via kg-manage. I'll have a look at it and maybe do a pull request.

**Comment by brianmay** [comment]
Thinking out loud: If I were to add code to allow emailing a specific project or a specific software (i.e. the users), would this be sufficient?

**Comment by DanielTosello** [comment]
Yeah, i think it probably would.

**Comment by brianmay** [comment]
This makes some changes to how project leader emails work. Will push to karaage-test - maybe tomorrow -  so you can test and let me know if you are happy with the changes.

**Comment by brianmay** [comment]
Now on karaage-test.

Note now one email sent to every person. This is different to before (I think), where if "project leaders" was selected there would be one email for every project.

As a result this means a person may lead multiple projects. All of these projects will get listed in the `{{projects}}`` value (comma separated).

I think this is perhaps a better outcome as it minimizes the number of emails received. However possible it may require tweaking. Feedback welcome.

The list of people can now be filtered based their institute and/or projects that they belong to. If the value is left empty, then the filter does not apply.
