### ISSUE TITLE
Users with old style passwords not allowed to request password reset email

### ISSUE THREAD

**Issue by richardnixonshead** [Karaage-Cluster/karaage#542]
We have found with the Karaage used by Spartan that some users still have the old style passwords in their account

e.g.

`!blahblahblah`

If a user has this as their password, instead of the 

`bcrypt_sha256$$2b$12$blahblahblah`

they cannot request a password reset email. They get to the screen to request a password reset email, and click the button, but the button does not work.

I think it is due to

https://github.com/Karaage-Cluster/karaage/blob/7bf3be8f49a2663cf9c8f0e9c43478a07ad2f820/karaage/people/views/profile.py#L235

```
@login_required
def password_request(request):
    person = request.user

    post_reset_redirect = reverse('kg_profile_reset_done')

    if request.method == "POST":
        if person.has_usable_password():
            send_reset_password_email(person)
            return HttpResponseRedirect(post_reset_redirect)
```

I think the `person.has_usable_password():` should be removed

There was a similar issue fixed by commit 25e63db38e8b74ef5ff29bcae55396bb0a9cbc7f that fixed the same logic in a couple of places, but not this one

**Comment by brianmay** [comment]
Seems like this might have actually been a Django bug: https://docs.djangoproject.com/en/2.1/ref/contrib/auth/#django.contrib.auth.models.User.has_usable_password

>  Changed in Django 2.1:
> In older versions, this also returns False if the password is None or an empty string, or if the
> password uses a hasher that’s not in the PASSWORD_HASHERS setting. That behavior is
> considered a bug as it prevents users with such passwords from requesting a password reset.

I don't think there is any hurry to change this however.
